#!/bin/bash

echo "Setting up ubuntu packages and updates"

# Update all packages
sudo apt update -qq -y
sudo apt upgrade -qq -y

# Basic packages
sudo apt install -qq -y curl git tmux vim wget zsh

# Display managers
sudo apt install -qq -y gnome-common i3 compton

# General utilities
sudo apt install -qq -y htop mutt ncdu ranger w3m w3m-img zip

# Programming
sudo apt install -qq -y gcc python python3 python-pip python3-pip

# Document stuff
sudo apt install -qq -y texlive zathura 

# Media
sudo apt install -qq -y mpv

# Install ugly programs as snaps
echo "Setting up snap packages"
sudo snap install discord mailspring viber-unofficial
