#!/bin/bash

echo "Setting up ubuntu packages and updates"

# Update all packages
sudo apt update
sudo apt upgrade

# Basic packages
sudo apt install -qq -y curl git tmux vim wget zsh

# Display managers
sudo apt install -qq -y gnome-common i3

# General utilities
sudo apt install -qq -y mutt ncdu ranger zip

# Programming
sudo apt install -qq -y gcc python python3 python-pip python3-pip

# Document stuff
sudo apt install -qq -y texlive zathura 

# Media
sudo apt install -qq -y mpv
